### ISSUE TITLE
Feature Request: Data orientated languages and offline mode

### ISSUE THREAD

**Issue by MfundoZA** [Jeusto/warm-up-vscode#3]
I'm really enjoying using this extension however I think it could be improved by caching maybe  one or two natural languages that the user types in as well as their primary programming language(s) so that it could be used without an internet connection.

I also think it would be a good idea to include data orientated languages such as SQL (and it's variants) and NOSQL languages like MongoDB.

**Comment by Jeusto** [comment]
The extension should work offline, did I misunderstood you ? Data oriented languages, I'll add them for sure, in the meantime you can use the `practiceWithSelection` command
